# Use an official Python runtime as a base image
FROM python:3.10.12-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file into the container and install the dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt && echo "Dependencies installed successfully"

# Copy the entire project into the container
COPY . /app

# Run your application (update the command based on how you launch the app)
CMD ["python", "audioprocessor.py"]